### ISSUE TITLE
A module for /etc/login.conf

### ISSUE THREAD

**Issue by arrowd** [dlundgren/ansible-freebsd-modules#15]
Hello. I have a need to edit some values in `/etc/login.conf` file and rebuild the database after that.

It would be great to have a module for this task. It may look like

```
login_conf:
  - class: default
      insert: ":lang=ru_RU.UTF-8:", ":charset=UTF-8:"
      append:
          - setenv: "HTTP_PROXY=asdasd"
```
