### ISSUE TITLE
Add the ability to add custom values to /boot/loader.conf

### ISSUE THREAD

**Issue by chrisb86** [dlundgren/ansible-freebsd-modules#19]
Hi.

I'm writing a role that needs to write custom values to loader.conf.
```
 cpu_microcode_load="YES"
 cpu_microcode_name="/boot/firmware/intel-ucode.bin"
 ```
As I see in the documentation, I can't set the second line with kld. Right?
Would it be possible to add this? I don't know python so I can't help here.

Best regards
Chris

**Comment by chrisb86** [comment]
Figured it out.

**Comment by basbebe** [comment]
@chrisb86  How did you end up doing this?

**Comment by dlundgren** [comment]
You can use the [community.general.sysrc](https://docs.ansible.com/ansible/latest/collections/community/general/sysrc_module.html)  module to handle this.

Example:
```yaml
- name: Add microcode
  community.general.sysrc:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    file: /boot/loader.conf
  with_dict:
    cpu_microcode_load: "YES"
    cpu_microcode_name: "/boot/firmware/intel-ucode.bin"
```
