### ISSUE TITLE
Sysrc append treats multiword-values as multiple single values

### ISSUE THREAD

**Issue by KizzyCode** [dlundgren/ansible-freebsd-modules#20]
Sysrc treats word combinations like `addm em0` and `addm epair0a` etc. as multiple single words.

E.g. the actions:
```
- name: Add jail to vnet
  sysrc: name="{{ item.name }}" value="{{ item.value }}" state="{{ item.state }}"
  loop:
    - { name: ifconfig_bridge0, value: "addm em0", state: append }
    - { name: ifconfig_bridge0, value: "addm epair0a", state: append }
```

What I want to achieve is `ifconfig_bridge0="addm em0 addm epair0a"`; however both `sysrc`-CLI and the `sysrc` module create `ifconfig_bridge0="addm em0 epair0a"`, which obviously does not have the intended effect (`epair0a` is not attached).

Is there any way/workaround to append multi-word values to an existing key?

**Comment by dlundgren** [comment]
A workaround, though not so pleasant at the moment, would be to combine them independently of sysrc. 

```yaml
- set_fact:
    addm_ifs:
      - em0
      - epair0a
- sysrc:
    name: ifconfig_bridge0
    value: "{% for if in addms_ifs %}addm {{ if }} {% endfor %}"
```

I'll take a look at how this could be supported in the module, I'm surprised this hasn't been fixed in `sysrc`-CLI itself.

Do you happen to know if the arguments to `ifconfig_bridge` are required to be in a certain order? If they are I'm wondering if it'd be worth it to create a module that deals specifically with creating the bridge interfaces.
