### ISSUE TITLE
kld insists on using controller python version on target host

### ISSUE THREAD

**Issue by greyghost509** [dlundgren/ansible-freebsd-modules#21]
I ran into an issue these days with kld when the python versions of the ansible controller and the target system to be configured did not match:

> failed: [fastback] (item=aesni) => {"ansible_loop_var": "item", "changed": false, "item": "aesni", "module_stderr": "/bin/sh: /usr/local/bin/python3.9: not found\n", "module_stdout": "", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127}

In this case, the controller had python3.9 and insisted on using this on the target, too. However, the client had only python3.11 available. Setting explicitely `ansible_python_interpreter=/usr/local/bin/python3` does not change this behaviour, it still insists on using python 3.9 on the target. The task causing this issue is

```
- name: unload kernel modules from boot
  kld:
    name: "{{ item }}"
    load: false
    boot: false
  loop: "{{ kld_unlist | default([]) }}"
```

The kld version installed is py39-ansible-kld from FreeBSD's pkg (version g20200803,1).
